services:
  mongodb:
    image: mongo:latest # Official MongoDB image
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: password # Set the root password
  mongo-express: # Optional: Add Mongo Express for a web-based UI
    image: mongo-express:latest
    container_name: mongo-express-container
    restart: always
    ports:
      - "8081:8081" # Expose Mongo Express on port 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
